# =============================================================================
# Inputs:
#   Variable name                     Sample value                  Description
#   ---------------------------------------------------------------------------
#   USERNAME
#   PASSWORD                                                        CR_PAT
#   DOCKERFILE
#   IMAGE                             node_base:123-staging
#   CACHE_FROM
#
# Steps:
#   1. Login to Registry
#   2. Build docker image and push to registry
#
# Sample image: ghcr.io/oneamo/[IMAGE]
#
# =============================================================================

name: Build static files action

inputs:
  USERNAME:
    description: "USERNAME"
    required: true
  PASSWORD:
    description: "PASSWORD"
    required: true
  IMAGE:
    description: "IMAGE"
    required: true
  DOCKERFILE:
    description: "DOCKERFILE"
    default: "./dockerfiles/eks_node_14_15_1_alpine_x86.Dockerfile"
  CACHE_FROM:
    description: "CACHE_FROM"

outputs:
  image:
    description: "Image name"
    value: ghcr.io/oneamo/${{ inputs.IMAGE }}

runs:
  using: "composite"
  steps:
    # Step 1: Login
    - name: Login to Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ inputs.USERNAME }}
        password: ${{ inputs.PASSWORD }}

    # Step 2: Build image and push to registry
    - name: Docker build & push node base
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ${{ inputs.DOCKERFILE }}
        tags: ghcr.io/hieuhuynhdev/${{ inputs.IMAGE }}
        push: true
        cache-from: type=registry,ref=ghcr.io/hieuhuynhdev/${{ inputs.CACHE_FROM }}
        cache-to: type=inline
