# ========================================================================================
# List Github secrets with sample values:
#   Secret variables                            Sample values                  Description
#   --------------------------------------------------------------------------------------
#   STAGING_APP_ENV                             NODE_ENV=staging
#   CR_PAT
#
# Deployment flow:
#   1. Pull latest source code
#   2. Validate source code
#   3. Build and push image
# ========================================================================================

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
        default: 1-staging

env:
  PYTHON_VERSION: "3.11"
  APP_ENV: ${{ secrets.STAGING_APP_ENV }}

  CR_PAT: ${{ secrets.CR_PAT }}
  IMAGE_TAG: ${{ github.event.inputs.version }}

name: Manual Build STAGING python base image

jobs:
  main:
    name: Build image version ghcr.io/oneamo/python_base:${{ github.event.inputs.version }}
    runs-on: ubuntu-20.04

    steps:
      # Step 1: Pull source code and install dependencies
      - name: Pull source code and install dependencies
        uses: hieuhuynhdev/python-base/.github/actions/pull-source-and-install-dependencies@main
        with:
          BRANCH_NAME: ${{ github.ref_name }}
          PYTHON_VERSION: ${{ env.PYTHON_VERSION }}
          APP_ENV: ${{ env.APP_ENV }}

      # Step 2: Validate source code
      - name: Validate source code
        uses: ./.github/actions/validate-source-code

      # Step 3: Build and push image
      - name: Build and push image
        id: docker-image
        uses: ./.github/actions/build-and-push-image
        with:
          USERNAME: ${{ github.repository_owner }}
          PASSWORD: ${{ env.CR_PAT }}
          IMAGE: python_base:${{ env.IMAGE_TAG }}
          DOCKERFILE: ./dockerfiles/eks_python_3_16_alpine.Dockerfile
